version: "3.9"

services:

  otc-prometheus-exporter:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - "./docker.local/otc-prometheus-exporter:/root"

    environment:
      NAMESPACES: "SYS.ECS"
      PROJECT_NAME: "eu-de_iits-central"
      PORT: 8000

  prometheus:
    image: "prom/prometheus:latest"
    ports:
      - "9090:9090"
    command:
       - '--config.file=/tmp/prometheus/prometheus.yaml'
    volumes:
      - "./docker.local/prometheus:/tmp/prometheus"

  grafana:
    image: "grafana/grafana:latest"
    ports:
      - "3000:3000"
