image:
  imageRepository: "ghcr.io/iits-consulting"
  imageTag: "v0.4.0"


osUsername: ""
osPassword: ""
osAccessKey: ""
osSecretKey: ""
osProjectId: ""
osDomainName: ""
namespaces: ""
metricsPort: 39100
waitDuration: 60
fetchResourceIdToName: false

serviceMonitor:
  enabled: false 
  labels:
    release: kube-prom
